### ISSUE TITLE
学分成绩“重修”段显示错误

### ISSUE THREAD

**Issue by kaaass** [yang-er/HandSchool#1]
# 该问题是怎么引起的？
查询学分成绩时。

# 复现步骤
前提：网页查询时，重修段为空。如下图所示。
![qq 20190106193004](https://user-images.githubusercontent.com/13360135/50735425-d62f7f80-11e9-11e9-8440-a145a8735c87.png)

1. 进入“学分成绩”页。
2. 选择重修段为空的课程。

![screenshot_20190106-192745](https://user-images.githubusercontent.com/13360135/50736012-3c200500-11f2-11e9-99c2-5841cdd9931b.jpg)

# 测试环境

HandSchool 1.6.15.0
Android 8.0.0

# 报错信息

无

# 修正建议

[此处代码](https://github.com/yang-er/HandSchool/blob/491fcfa8034789b62ca594409a362f67300ed736/HandSchool/HandSchool/JLU/Grade.cs#L32)的判断建议改为判断是否为"Y"，或增加对非预期输入null的处理。

# 备注

由于个人水平有限，就不发PR丢人了。

**Comment by yang-er** [comment]
We'll fix it in the next version.
