### ISSUE TITLE
一直登陆不上

### ISSUE THREAD

**Issue by creater-yzl** [yang-er/HandSchool#3]
我在校内网jlu.net，关了学生vpn，软件是最新版。然后它总提示“uims服务器出了问题”，然后错误是什么什么loginerror 请问怎么办呢

**Comment by creater-yzl** [comment]
呃又好了，没事了，谢谢朋友们

**Comment by XhL6996** [comment]
挖个坟，应该是当时登录错误的提示坏了，不管你是账号密码错误还是验证码错误，都会提示服务器返回信息有问题。
