### ISSUE TITLE
[Feature request] Adaptive Icons

### ISSUE THREAD

**Issue by ghost** [yang-er/HandSchool#4]
现在这方图标太难看了，很多 launcher 都是圆的结果就导致外面又一圈框。
![Screenshot_20211102-124714](https://user-images.githubusercontent.com/64400759/139788459-643d522e-82f5-4fc5-8258-c6ba1f61f50b.jpg)
试着用 [IconKitchen](https://icon.kitchen/) 搞了一个，希望能改改，谢谢！
[android.zip](https://github.com/yang-er/HandSchool/files/7457915/android.zip)

ref: https://dev.to/sfarias051/how-to-create-adaptive-icons-for-android-using-android-studio-459h

**Comment by XhL6996** [comment]
感谢提议，此特性将在下一个版本应用。
